### ISSUE TITLE
non-binary text

### ISSUE THREAD

**Issue by er1p** [ajdavis/twitter-gender-ratio#1]
you might consider being more generous with the pronoun search to catch the following variations:
- "pro-nouns" as a synonym for "pronoun"
- the string "they/them" even without the word pronoun, plus "them/they"

OTOH, if you are too generous with the string "pronoun", you might pick up:
- "pronounced 'ree-del'  " and similar guidance about name pronunciation

not sure what you would do with:
- "she or they for pronouns"; "she/her/they"; "they/she"; "he/they"

that's all the obvious stuff from my followers, followings

nice app, nice start

**Comment by ajdavis** [comment]
Thanks for the feedback! Sorry I didn't notice until now. The code doesn't look for the string "pronoun" in the Twitter profile at all, it only looks for "he", "she", "they" as words:

https://github.com/ajdavis/twitter-gender-distribution/blob/master/analyze.py#L44

So far this seems like the best heuristic I can find for detecting when people declare their pronouns in Twitter profiles.
