### ISSUE TITLE
Feature suggestion - Sample timeline for gender balance 

### ISSUE THREAD

**Issue by josephlord** [ajdavis/twitter-gender-ratio#12]
Different people tweet at different frequencies so the gender balance of content may differ from that of the number of followers. Might be nice to show that figure as additional information. Maybe review last 100 tweets or something like that.

**Comment by ajdavis** [comment]
That's an interesting idea! Want to try implementing it? =)

**Comment by Kudusch** [comment]
I'd be interested in this too and could try to implement it. Do you take pull requests?

**Comment by ajdavis** [comment]
Yes!

**Comment by jampo** [comment]
any update @Kudusch  would love to see this feature :+1:

**Comment by ajdavis** [comment]
Pull requests welcome! I don't plan to implement this feature myself.

**Comment by Kudusch** [comment]
@jampo Thank you for the reminder! 

I tested the CLI and the flask-server, both seem to work fine.

**Comment by ajdavis** [comment]
Now deployed on https://www.proporti.onl/, thanks for the contribution!
