### ISSUE TITLE
Feature suggestion - analyze twitter lists

### ISSUE THREAD

**Issue by xgebi** [ajdavis/twitter-gender-ratio#13]
I do have half of my timeline in a twitter list because it's just too fast when I have ~1000 accounts in one column. Two columns are more readable for some reason. Could you, please, add support for Twitter lists?

**Comment by ajdavis** [comment]
That's a good idea. Do you know Python, do you want to give it a try yourself?

Otherwise, can you point me to Twitter API documentation for retrieving lists?

**Comment by xgebi** [comment]
If I knew Python, I would be working on it.

I think I can do better, here is a place where you can retrieve all lists and another where you can get members of that list
https://developer.twitter.com/en/docs/accounts-and-users/create-manage-lists/api-reference/get-lists-list
https://developer.twitter.com/en/docs/accounts-and-users/create-manage-lists/api-reference/get-lists-members

**Comment by ajdavis** [comment]
Thanks for the pointers!

**Comment by ajdavis** [comment]
This is deployed now, please let me know how it works for you.
