### ISSUE TITLE
Check for pronoun.is links

### ISSUE THREAD

**Issue by strugee** [ajdavis/twitter-gender-ratio#15]
Some folks like to link to http://pronoun.is/ to declare their pronouns.

Thanks for writing this tool, it seems pretty awesome :heart:

**Comment by ajdavis** [comment]
It should work already:

https://github.com/ajdavis/twitter-gender-distribution/blob/master/analyze.py#L83

Do you have any evidence that it isn't?

Thanks!

**Comment by strugee** [comment]
Whoops, didn't realize that! I was going off the algorithm description in https://emptysqua.re/blog/gender-of-twitter-users-i-follow/, which doesn't mention it unless I missed something.

So sorry for the noise!

**Comment by ajdavis** [comment]
No worries, the code keeps evolving and I'm not updating the article assiduously.
