### ISSUE TITLE
TypeError: analyze_friends() takes exactly 6 arguments (5 given)

### ISSUE THREAD

**Issue by introllo** [ajdavis/twitter-gender-ratio#16]
Running the app locally with Python 2.7.14 (as root)
After the "Enter your pincode?" prompt, I see:

Generating and signing request for an access token...

          	 nonbinary	       men	     women	   unknown
Traceback (most recent call last):
  File "analyze.py", line 356, in <module>
    tok, tok_secret)),
TypeError: analyze_friends() takes exactly 6 arguments (5 given)

I ran in debug mode (-vv) and didn't see anything interesting before the program dumped. Thoughts?

**Comment by introllo** [comment]
the unit test fails, thusly:

# python2.7 -m unittest discover -v
test_declared_gender (tests.test_declared_gender.TestDeclaredGender) ... FAIL

======================================================================
FAIL: test_declared_gender (tests.test_declared_gender.TestDeclaredGender)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/twitter-gender-distribution/tests/test_declared_gender.py", line 50, in test_declared_gender
    description, expected_gender, guess))
AssertionError: Should have guessed profile 'mum to one boy and one girl' was 'female', not 'male'

----------------------------------------------------------------------
Ran 1 test in 0.115s

FAILED (failures=1)

**Comment by ajdavis** [comment]
This sounds like two different bugs. For the first bug, "TypeError: analyze_friends() takes exactly 6 arguments (5 given)", it looks like I added a parameter to analyze_friends() and didn't update its caller. This works in the web application at https://proporti.onl but not on the command line. Would you like to submit a pull request?

For the second issue, that's a separate bug. Please open it as a new issue.

Thanks!
