### ISSUE TITLE
Adapt project for use with Mastodon?

### ISSUE THREAD

**Issue by scotthmurray** [ajdavis/twitter-gender-ratio#17]
Thank you for this fantastic project! I stumbled upon this while researching how to do the same thing myself, so… you saved me a ton of time. 😀 

Would you consider adapting and/or expanding this project to also work with Mastodon (not just Twitter)?  Mastodon is interesting as it's attempting to be a much safer and more welcoming online social space. A number of queer and non-gender-conforming communities, in particular, have sprung up, in part because Mastodon tends to me a more welcoming space.  So I think it would be interesting and valuable to extend similar logic to Mastodon accounts or instances.  Mastodon has APIs built in, similar to Twitter's, so it's theoretically possible, but would require effort, naturally.  I can help put out the call for people with Python experience (i.e., not me) who would volunteer to take this on.

Selfishly, I am exploring ways to increase the gender diversity of my own instance, vis.social. If you're interested, we have a bit of discussion going on over there: https://vis.social/@scott/99920973290832650

**Comment by ajdavis** [comment]
Hi! I'm not personally interested in doing so. But I'd be excited if you recruit someone to fork the project for Mastodon. Or, if someone makes a pull request that makes this project work for both Twitter and Mastodon then I could offer support for both networks on proporti.onl.

**Comment by scotthmurray** [comment]
OK, fantastic. I will ask around. Thank you!
