### ISSUE TITLE
consider updated name database

### ISSUE THREAD

**Issue by er1p** [ajdavis/twitter-gender-ratio#2]
the names database described at the following link looks to be newer than the python library that you are using (still US-centric, and not obvious whether the age-related aspect would be useful to you):

https://cran.r-project.org/web/packages/gender/vignettes/predicting-gender.html

I found the above link based on a paper that I saw presented earlier this week at a security & privacy conference:

https://www.usenix.org/system/files/conference/soups2016/soups2016-paper-mondal.pdf

(Section 3.3.2 describes these researchers' approach to gender discovery)

**Comment by ajdavis** [comment]
My much belated response is that, since my tool is written in Python and the library you linked to is in R, I'm going to stick with the library I use. If you find or create a better Python gender-guessing library please let me know!
