### ISSUE TITLE
Broken unit test: “Should have guessed profile 'mum to one boy and one girl' was 'female', not 'male'”

### ISSUE THREAD

**Issue by lucaswerkmeister** [ajdavis/twitter-gender-ratio#20]
Split off from https://github.com/ajdavis/twitter-gender-distribution/issues/16#issuecomment-378813452.

```
$ python2.7 -m unittest discover -v
test_declared_gender (tests.test_declared_gender.TestDeclaredGender) ... FAIL

======================================================================
FAIL: test_declared_gender (tests.test_declared_gender.TestDeclaredGender)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/twitter-gender-distribution/tests/test_declared_gender.py", line 50, in test_declared_gender
    description, expected_gender, guess))
AssertionError: Should have guessed profile 'mum to one boy and one girl' was 'female', not 'male'

----------------------------------------------------------------------
Ran 1 test in 0.080s

FAILED (failures=1)
```

**Comment by lucaswerkmeister** [comment]
`git bisect` says that f2725606923164be1436789febbde6bf99cd1d54 is the first bad commit. (Part of #10, so CC @raptortech-js.)

**Comment by jackie-scholl** [comment]
Yup, looks like I did that! You can definitely fix it by reverting part or all of https://github.com/ajdavis/twitter-gender-distribution/commit/f2725606923164be1436789febbde6bf99cd1d54, though if you do that you will break, e.g., "guy who loves his mum." I'm not sure which formulation is more common, so I don't know if it makes more sense to change the test or change (back) the priority order

Regardless, I have no personal stake and I'm happy with whatever ends up happening :)

**Comment by ajdavis** [comment]
Let’s say, if there is more than one gender clue in the profile text, then
guess using first name as if there were no gender clues.
