### ISSUE TITLE
Check for gender declarations in bio

### ISSUE THREAD

**Issue by serin-delaunay** [ajdavis/twitter-gender-ratio#3]
At the moment `declared_gender()` checks only for pronouns. It might be a good idea to look for gender identities in the bio, for instance "non-binary", "nonbinary", "woman", "genderfluid", etc.
There are users who declare a gender on their bio but don't mention pronouns. If a user declares a nonbinary gender then that should take priority over any pronouns they declare.

**Comment by ajdavis** [comment]
Good idea, I'll add this.
