### ISSUE TITLE
Explain gender coding in the docs

### ISSUE THREAD

**Issue by patcon** [ajdavis/twitter-gender-ratio#30]
This is a great project! I appreciate the attempt :)

Just wanting to point out that some of your assumptions could perhaps be made clear to those who can't/won't read code, like this stuff:

https://github.com/ajdavis/twitter-gender-distribution/blob/9281de2e7ba088cfac7b908d22ae3385747876c1/analyze.py#L114-L117

From sources like this: https://nonbinary.wiki/w/index.php?title=Pronouns#/editor/0

> The use of binary pronouns doesn't necessarily mean that someone has a binary gender identity.

I feel its probably ok to simplify, but maybe good to be straightforward in layspeak about what those simplifications are, so others can thoughtfully critique (and maybe improve) this codebase :tada: 

Disclaimer: not non-binary myself, though folks in my circles are.

**Comment by ajdavis** [comment]
Thanks! I've linked to nonbinary.wiki from my blog post that explains the algorithm. I think the sentence there is sufficiently noncommittal:

> a description with "they/them" is probably nonbinary.
