### ISSUE TITLE
Check for more pronouns

### ISSUE THREAD

**Issue by serin-delaunay** [ajdavis/twitter-gender-ratio#4]
At the moment `declared_gender()` checks for he, she, and they as pronouns delimited by slashes, and expects any other pronouns to be specified using pronoun.is (which is ignored if there's also a pronoun.is/[s]he link in the bio).
There are Twitter accounts which declare (for instance) zie/hir pronouns, and don't include they as an alternative, and don't use any pronoun.is links, and such bios should probably be marked as nonbinary.  If there are concerns about clashes with non-English words, the algorithm could require at least 2 declensions of the same pronoun.
There may also be users who delimit their pronouns with commas.

Sorry, hit the wrong button on the mobile interface!

**Comment by ajdavis** [comment]
Agreed, I'll do this.
