### ISSUE TITLE
Is there a way to get around having to enter a Twitter consumer key and secret?

### ISSUE THREAD

**Issue by lauraluebbert** [ajdavis/twitter-gender-ratio#43]

**Comment by ajdavis** [comment]
To my knowledge, no. To use the Twitter API you must make a Twitter application, which identifies itself to Twitter using a consumer key and secret. [More info here](https://developer.twitter.com/en/docs/apps/overview):

> Accessing the Twitter API and Twitter Ads API requires a set of [authentication](https://developer.twitter.com/en/docs/authentication) credentials, also known as keys and tokens, that you must pass with each request.

Please reopen this ticket if you need more info or have a suggestion for avoiding this requirement.
