### ISSUE TITLE
proporti.onl HTTPS certificate has expired

### ISSUE THREAD

**Issue by reacocard** [ajdavis/twitter-gender-ratio#9]
Chrome says "There are issues with the site's certificate chain (net::ERR_CERT_DATE_INVALID)"

Expiry date was Thursday, September 21, 2017 at 5:49:00 AM

**Comment by ajdavis** [comment]
Thanks. I have got to find a better way of managing letsencrypt certs on PythonAnywhere.

**Comment by ajdavis** [comment]
Fixed, and I'm going to move to a 3-year signed certificate instead of Let's Encrypt. Thanks for the heads up.
